version: '3.7'

services:
  web:
    image: pawan_docker
    ports:
      - "81:80" #apache2
      - "23:22" #ssh
      - "8081:8080" #code Server Vscode
    volumes:
      - ./app:/var/www/html
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5' # Hard limit
